[WEBSITE-1115] Fix for houses current members and current members letters
ukparliament/parliament.uk-prototype pull request #424
Opened 2017-05-11 11:09 UTC by katylouise

* Made a few changes to the actions in the controller.
* Updated specs.

2017-05-11 12:32 UTC, mattrayner requested changes

2017-05-11 12:32 UTC, mattrayner commented on spec/controllers/houses_controller_spec.rb
> +      get :current_members_letters, params: { house_id: 'm1EgVTLj/', letter: 'a' }
should this have a / in it?

2017-05-11 12:51 UTC, katylouise commented on spec/controllers/houses_controller_spec.rb
> +      get :current_members_letters, params: { house_id: 'm1EgVTLj/', letter: 'a' }
whoops!

2017-05-15 11:50 UTC, mattrayner approved these changes

2017-05-15 11:51 UTC, merged