[WEBSITE-1260] Ensure that only the first house membership status is …
ukparliament/parliament.uk-prototype pull request #457
Opened 2017-05-31 15:06 UTC by bryonywatson1

…capitalised

* Add view helper with method to amend array of house membership statuses, only capitalising the first
* Amend view showing a House member to use the above method
* Add tests for the above method
* Amend existing tests to account for new logic

created view helper to convert house membership status and updated Member of House of Lords and former MP scenario using new method

2017-05-31 15:15 UTC, mattrayner requested changes

2017-05-31 15:15 UTC, mattrayner commented on app/views/people/show.html.haml
> +            - if @person.statuses[:house_membership_status].include?('Member of the House of Lords')
Can this be improved to use a language string?

2017-06-01 14:12 UTC, bryonywatson1 commented on app/views/people/show.html.haml
> +            - if @person.statuses[:house_membership_status].include?('Member of the House of Lords')
There's another change (website-1248) that removes all this logic which would make this change redundant, so we are going to leave it for now

2017-06-06 10:30 UTC, mattrayner commented on app/helpers/view_helper.rb
> +      if index != 0
try making this a one liner:
`statement if x == y`

2017-06-06 10:33 UTC, mattrayner approved these changes

2017-06-06 13:54 UTC, closed without merging